### ISSUE TITLE
Out of Sync developement

### ISSUE THREAD

**Issue by k-kruusi** [k-kruusi/GameBase#9]
Please delete any old branches your not using from the server (if your permissions don't allow it let me know what ones you don't want and ill remove them)

Right now i see work being done on:
Space-X-Defense-Program Updated 19 hours ago by Haifeng 
but your xcode project is on another one:
Space-X-Haifeng Updated 3 days ago by SuHaifeng

Its fine to have extra branches, but you can branch from your branch. You dont need to start a fresh one from the master branch.

**Comment by SuHaifeng** [comment]
I was only updating the ReadMe file.

**Comment by k-kruusi** [comment]
Right but notice how this branch: https://github.com/k-kruusi/GameBase/tree/Space-X-Defense-Program
doesn't have your xcode project?

**Comment by Otomai** [comment]
If you could please delete the Al3nsGame branch, thanks!

**Comment by SuHaifeng** [comment]
Ive added the base project to the main branch.
